import React from 'react';
import { Manrope } from 'next/font/google';

import 'app/[lang]/globals.css';
import { Menu } from '../../ui/menu/menu';
import { getDictionary } from '../../i18n/get-dictionary';
import { Locale } from '../../utils/types';

const manrope = Manrope({
  display: 'swap',
  subsets: ['latin'],
  variable: '--font-manrope',
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = async ({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { [key: string]: Locale };
}) => {
  const t = await getDictionary(lang);

  // --- HELPERS ---

  // --- RENDER ---

  return (
    <html className={manrope.variable} lang={lang}>
      <body className="p-4 text-black-900 min-h-screen box-border">
        <Menu headline={t(`pages.home.headline`)} />

        {children}
      </body>
    </html>
  );
};

export default RootLayout;
