import React from 'react';
import { Manrope } from 'next/font/google';

import 'app/[lang]/globals.css';
import { Menu } from 'ui/menu/menu';
import { getTFunction } from 'i18n/get-t-function';
import { Locale, Page } from 'utils/types';

const manrope = Manrope({
  subsets: ['latin'],
  variable: '--font-manrope',
});

export const metadata = {
  description: 'Generated by create next app',
  title: 'Create Next App',
};

const RootLayout = async ({
  children,
  params: { lang },
}: {
  children: React.ReactNode;
  params: { [key: string]: Locale };
}) => {
  const t = await getTFunction(lang);

  // --- HELPERS ---

  const menuOptions = [
    { translation: t('pages.home.menuOption'), page: Page.HOME },
    { translation: t('pages.settings.menuOption'), page: Page.SETTINGS },
    { translation: t('pages.history.menuOption'), page: Page.HISTORY },
    { translation: t('pages.statistics.menuOption'), page: Page.STATISTICS },
  ];

  // --- RENDER ---

  return (
    <html className={manrope.variable} lang={lang}>
      <body className="box-border p-4 tracking-wide text-black-900">
        <Menu headline={t(`pages.home.headline`)} menuOptions={menuOptions} />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
