name: App CI

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_FORCE_NO_BUILD_CACHE: 1

on:
  push:
    branches: [ "main" ]

jobs:
  eslint-build:
    name: eslint-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: heh1
        run: ls

      - name: hehe2
        run: pwd

      - name: initialize-ci
        uses: ./.github/template/initialize/action.yml

      - name: Build Eslint
        working-directory: ./packages/eslint-plugin-interval-app-styleguide
        run: pnpm initialize

  next-build:
    needs: eslint-build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: initialize-ci
        uses: ./.github/template/initialize/action.yml
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Install dependencies
        run: pnpm i

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Pull Vercel Environment Information
        working-directory: ./intervalApp
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts (frontend)
        working-directory: ./intervalApp
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts (frontend) to Vercel
        working-directory: ./intervalApp
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
